### ISSUE TITLE
Configured in only one file

### ISSUE THREAD

**Issue by cn-src** [krasa/EditorGroups#4]
Configured in only one file, there are groups in the file.

example:
```
@group-one.related ./*
@group-two.related *.txt
@group-two.related file.*
```

or

```
[group-one]
related ./*
related *.txt

[group-two]
related file.*
```

or use `yaml`

**Comment by krasa** [comment]
multiple groups are possible like so:

https://github.com/krasa/EditorGroups/blob/938cae4143fbd8facacddcd6a13c96e829273236/src/krasa/editorGroups/this.egroups
