### ISSUE TITLE
Can we have autogroups by regex? 

### ISSUE THREAD

**Issue by kool79** [krasa/EditorGroups#5]
Plugin is excelent!! 
But can we have autogroups by regex? 
For example I have several files inside one package:

- MySomePage
- MySomePageUI
- MySomePageGB

I want to see all those files inside one auto-group and ignore other files (like MySomeOtherPage.java) from the same package. Dont know how to implement it. One of the idea: User should define ordered list of regexps.  Regexp which matches to currently selected tab should be used to select all other files into auto-group.  If this regexp contains named group then all other files must have the same values for those groups.
Example: regexp:  `^(?<prefix>My.*)(?<middle>Page).*\.java`
  When file MySomePage.java is opened then current regexp matches and has 2 named groups: `prefix` (with value = 'MySome')  and `middle` (with value='Page')
   So all other files which match to this regexp must also  contains the same values for 'prefix' and 'middle' (files: MySomePageUI.java, MySomePageGB.java) But, for example, file 'MySomeOtherPage.java'  must not be included because value for `prefix` = `MySomeOther` is not 'MySome'.

Also it will be good to define 'scope' for the regexp: 
 - single package  (so regexp will work for filenames only from current package)
 - current and all  "nested"  packages. For example, if I open file qa.com.mypackage.MyClass.java then it should match files in the curent package and all subpackages like `qa.com.mypackage.subpackage`, `qa.com.mypackage.subpackage.subsubpackage`

**Comment by krasa** [comment]
Sounds good. 
It will probably need to use a single package scope as a default for performance reasons.

**Comment by krasa** [comment]
So I implemented it, you can add them in settings, so far only globally. No need for naming them, it has no effect.

You can try it: https://github.com/krasa/EditorGroups/releases/download/0.22/EditorGroups.zip
