### ISSUE TITLE
Files are opened as `non-project`  if project opened from symlinked-folder (win7)

### ISSUE THREAD

**Issue by kool79** [krasa/EditorGroups#6]
When I switch file from groups-panel (both with mouse and with Ctrl+Alt+Shift+W)  the file is opened as non-project file: 
 - Navigation bar (View-appearence-navigation bar) contains absolute path to file (D:\dev\my-project) instead of path relative to module) 
 - it is write-protected by IDEA (with non-project file protection feature)
 - native IDEA's tab (with file name) does not show valid icon for file
 - I cannot locate file in the Project window when press "Scroll from source" button.
I tried to 'Reindex this file', 'Reindex all project'  from plugin, also tried  to 'Invalidate cache and restart', recompile project with idea, with maven - nothing helped.

**Steps to reproduce:**
00. (added) Create symlink (i.e `D:\dev`)  to any (parent) directory which contains your project (i.e. `D:\Dropbox\dev`). Open project from the symlinked directory (`D:\dev`)
0.  (not relevant) ~I have the java project with one module only. No *.egroups files. Initial state - no editor windows opened.~ 
1. Open file from project window. Result: File is opened, native IDEA's tab contains valid icon for file, I CAN locate this file in Project widow, Navigation bar contains valid path to file (relative to module). I.e. file is opened as 'project file'.   
   Below native tabs there is EditorGroup's tab with auto-group 'Current folder' -- it contains files from the same folder. See 
![screen1](https://user-images.githubusercontent.com/4625317/60521334-c05dcb80-9cef-11e9-977f-e47d5ae7bc96.png)

2. Click to any file(tab) on the EditorGroup's tab-bar.  
  **Expected result:** file is opened  as 'project' file: it can be located in 'Project' window, can be edited and so on (see ticket description above)
  **Actual result:** file is opned as non-project file (see ticket description above) 
![screen2](https://user-images.githubusercontent.com/4625317/60521820-8fca6180-9cf0-11e9-8f10-fbd8a6103d6c.png)

3. Return to file from step 1 by using EditorGroup's tab-bar (or Ctrl+Alt+Shift+W) .
   **Actual result**: file is opened as non-project file.  -- no able to edit etc.. 
![screen3](https://user-images.githubusercontent.com/4625317/60522111-0ebf9a00-9cf1-11e9-8168-c10741aad6aa.png)

Same issues for project files for other (non-source) folders, including 'same name' autogroup

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5438.14, built on June 26, 2019
IntelliJ IDEA EAP User
Expiration date: July 26, 2019
Runtime version: 11.0.3+12-b304.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by krasa** [comment]
Cannot reproduce, Could you attach a sample project, including IDE project files? Also, IDE version?

**Comment by kool79** [comment]
I've updated issue (1st version was posted by mistake with incomplete info) -- with screenshots, IDEA version. (Note: it is latest Ultimate  EAP version)
Unfortunately I cannot include my current project but will try to reproduce on  clean project.

**Comment by krasa** [comment]
Hmm, never seen such thing and cannot reproduce, - Win 10, same IDE.
Maybe there will be something interesting if you enable debug log with `#krasa.editorGroups`.

**Comment by krasa** [comment]
Try to use shift or alt +click to switch, that calls different methods and might make a difference.

**Comment by kool79** [comment]
Connot reproduce on clean project also ((
Will try to enable debug logging.
[editor-groups-passed.txt](https://github.com/krasa/EditorGroups/files/3350787/editor-groups-passed.txt)  -- log file for `clean`  project where there are no issues

[editor-groups-failed.txt](https://github.com/krasa/EditorGroups/files/3350790/editor-groups-failed.txt)
-- log file for my corrent project where I have issues 

In my 'clean' project I created sevaral files with the same class names (including package name).
Differences are:
  original project (with bug) is maven project,  and use git.
  new clean project is pure idea project (no maven)

Alt+Click opens files in splitted tab and have the same issues -- files are opened as non-project

Will try to disable other non-bundled plugins.

**Comment by krasa** [comment]
Do you use symlinks or something like that?

**Comment by krasa** [comment]
Maybe that Dropbox folder does it...

**Comment by kool79** [comment]
yes.. 
project is opened from D:\dev which is linked to D:\Dropbox\dev

**Comment by kool79** [comment]
Thanks for quick responces ))

I moved my 'clean' project into `D:\Dropbox\dev` and then open it from symlinked `D:\dev` - issue is reproduced. 
When I tried to open it from  `D:\Dropbox\dev`  -- then no issue. So workaround was found. ))

**Comment by kool79** [comment]
I've updated the title and Steps To Reproduce

**Comment by krasa** [comment]
From JetBrains dev: `using symlinks in project files is.. very discouraged` :-)

I will try to fix it.
