### ISSUE TITLE
Can't Delete TranslationEditor

### ISSUE THREAD

**Issue by 0LoveToLearn0** [krasa/EditorGroups#9]
![image](https://user-images.githubusercontent.com/35705818/67153187-afdb5c00-f2b2-11e9-82a5-d72fa85f045f.png)

I added it but I can't remove it or open it. 

Also, it would be nice to be able to delete a favorite list. (uninstalling and reinstalling doesn't work and I don't know where the files are)

Thank you!

**Comment by krasa** [comment]
It takes data from Favorites tool window (alt+2), try to open that file from there.
